---
title: "業績"
---

これまでの業績の一覧です。新しいものから並んでいます。

## 原著論文

**Keisuke ANDO**, Ryoya MAEDA, Haruki UEHARA, Joe FUJISAWA, Itsuki MATSUNAGA, Ryosuke SUZUKI, Kota KATO, Yuki SHIMADA, Shuntarou FUJII, Takeshi UCHITANE, Kazunori IWATA, Nobuhiro ITO, “Designing a Rescue Strategy Emphasizing Distributed Control in RoboCupRescue Simulation AIT-Rescue: RoboCup 2024 Rescue Simulation League Champion,” RoboCup 2024 Champion Paper, 2025

## 国際会議

**Keisuke ANDO**, Yusuke KUNIYOSHI, Natsuki ONOGI, Takeshi UCHITANE, Naoto MUKAI, Kazunori IWATA, Nobuhiro ITO and Yong JIANG, “Cluster Detection for Traffic Accidents on Spatiotemporal Networks,” 28th International Conference on Knowledge-Based and Intelligent Information & Engineering Systems (KES 2024), pp. 1--10, Sep, 2024, DOI: [10.1016/j.procs.2024.09.416](https://doi.org/10.1016/j.procs.2024.09.416)

Itsuki MATSUNAGA, Haruki UEHARA, Ryoya MAEDA, Joe FUJISAWA, Hiroya SUZUKI, **Keisuke ANDO**, Takeshi UCHITANE, Kazunori IWATA, Nobuhiro ITO, “Design of Task Assignments based on Ordering and Time Window Constraints for RoboCupRescue Agents,” IIAI AAI 2023 14th IIAI International Congress on Advanced Applied Informatics, IEEE, pp. 406--411, Sep, 2023, ロボカップ研究賞受賞

<a href="https://ieeexplore.ieee.org/document/10371606" class="icon-link">{{< fa solid link >}} リンク</a>
<a href="https://speakerdeck.com/nononoexe/design-of-geospatial-database-for-analysis-of-road-traffic-accidents-in-aichi-prefecture" class="icon-link">{{< fa brands speaker-deck >}} Speaker Deck</a>

Tomohiro MURAKAMI, Nozomi NAKAO, Hikaru MIYAKE, Hayate MURATA, Itsuki AMANO, Taisei KOJIMA, **Keisuke ANDO**, Nobuhiro ITO, “Effects of the Attunement of an Attack Target by Whispering in AIWolf,” IIAI AAI 2023 14th IIAI International Congress on Advanced Applied Informatics, IEEE, pp. 355--360, Sep, 2023

<a href="https://ieeexplore.ieee.org/document/10371657" class="icon-link">{{< fa solid link >}} リンク</a>

Masaki BAN, Takumi AMANO, **Keisuke ANDO**, Takeshi UCHITANE, Kazunori IWATA, Nobuhiro ITO, “Analysis of the Expected Possession Value in RoboCupSoccer Simulation 2D,” IIAI AAI 2023 14th IIAI International Congress on Advanced Applied Informatics, IEEE, pp. 293--298, Sep, 2023, ロボカップ研究賞受賞

<a href="https://ieeexplore.ieee.org/document/10371547/" class="icon-link">{{< fa solid link >}} リンク</a>

**Keisuke ANDO**, Yusuke KUNIYOSHI, Kazuhiko SHIMIZU, Takeshi UCHITANE, Naoto MUKAI, Kazunori IWATA, Nobuhiro ITO, Yong JIANG, “Spatio-temporal Network Analysis for Detecting Traffic Accident Clusters,” IIAI AAI 2023 14th IIAI International Congress on Advanced Applied Informatics, IEEE, pp. 257--262, Sep, 2023

<a href="https://ieeexplore.ieee.org/document/10371537" class="icon-link">{{< fa solid link >}} リンク</a>
<a href="https://speakerdeck.com/nononoexe/spatio-temporal-network-analysis-for-detecting-traffic-accident-clusters" class="icon-link">{{< fa brands speaker-deck >}} Speaker Deck</a>

**Keisuke ANDO**, Kazuhiko SHIMIZU, Nobuhiro ITO, Kazunori IWATA, Takeshi UCHITANE, Naoto MUKAI, Yong JIANG, “Design of Geospatial Database for Analysis of Road Traffic Accidents in Aichi Prefecture,” Proc. of Joint 12th International Conference on Soft Computing and Intelligent Systems and 23rd International Symposium on Advanced Intelligent Systems (SCIS&ISIS 2022), F-2-D-4, pp. 1--7, Dec, 2022, DOI: [10.1109/SCISISIS55246.2022.10002001](https://doi.org/10.1109/SCISISIS55246.2022.10002001)

**Keisuke ANDO**, Haruaki UEDA, Takeshi UCHITANE, Kazunori IWATA, Nubuhiro ITO , “Applying covariance structure analysis to reveal relationships between agent capability and map characteristics in RoboCup Rescue Simulation,”（原稿なし、発表のみ） 2021 Workshop on Artificial Intelligence and Simulation for Natural Disaster Management, Jul, 2021，ロボカップ研究賞受賞

<a href="https://cdn.robocup.org/rsim/public/workshops/2021-waisdm/andoEtAl2021-waisdm.pdf" class="icon-link">{{< fa solid link >}} リンク</a>

Takanori FUKUI, **Keisuke ANDO**, Toshihide MURAKAMI, Nobuhiro ITO and Kazunori IWATA, “Automatic Classification of Remarks in Werewolf BBS,” 2017 5th Intl Conf on Applied Computing and Information Technology/4th Intl Conf on Computational Science/Intelligence and Applied Informatics/2nd Intl Conf on Big Data, Cloud Computing, Data Science (ACIT-CSII-BCD), pp. 210--215, Jul, 2017

## 国内学会

藤澤 丈、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「反応閾値に基づくタスク割当手法のRoboCupRescueSimulationにおける有効性」、社会システムと情報技術研究ウィーク（WSSIT2025）、pp. 1--7、2025年3月

福田 遥生、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「RoboCup Soccer シミュレーションにおける混合モデルを用いたチーム分類法とその活用」、社会システムと情報技術研究ウィーク（WSSIT2025）、pp. 1--7、2025年3月

**安藤 圭祐**、内種 岳詞、向 直人、岩田 員典、伊藤 暢浩「日本における正面衝突事故と道路曲率の関係調査」、社会システムと情報技術研究ウィーク（WSSIT2025）、pp. 1--11、2025年3月

<a href="https://www.docswell.com/s/NONONOexe/KV18DP-wssit-2025" class="icon-link">{{< fa solid person-chalkboard >}} Docswell</a>

上原 温揮、島田 優希、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「RoboCupRescue SimulationのためのPythonを用いたエージェント開発フレームワーク」、社会システムと情報技術研究ウィーク（WSSIT2025）、pp. 1--7、2025年3月

前田 綾也、鈴木 涼介、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「RoboCupRescue Simulationの動的タスク割当手法に関する一考察」、社会システムと情報技術研究ウィーク（WSSIT2025）、pp. 1--8、2025年3月


上原 温揮、島田 優希、**安藤 圭祐**、内種 岳詞、向 直人、岩田 員典、伊藤 暢浩「RoboCupRescue Simulation における ADF-Python の実現について」（ポスター発表）、「社会におけるAI」研究会 第50回研究会、2024年11月

<a href="https://drive.google.com/file/d/1lZHH4qKlwnsShM-DbRVsOB8QNuTCVNXb/view" class="icon-link">{{< fa solid link >}} リンク</a>

松永 一希、藤井 駿太郎、加藤 幸太、**安藤 圭祐**、内種 岳詞、向 直人、岩田 員典、伊藤 暢浩「実験計画法を用いた災害救助エージェントの能力と救助結果との関係分析の検討」（ポスター発表）、「社会におけるAI」研究会 第50回研究会、2024年11月、最優秀プレゼンテーション賞受賞

<a href="https://drive.google.com/file/d/1I7r2qJKjX3MTopnppolh49jgBPkW4CET/view" class="icon-link">{{< fa solid link >}} リンク</a>

藤澤 丈、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「レスキューシミュレーションにおける多様な反応閾値を用いたタスク割当結果への影響」（ポスター発表）、「社会におけるAI」研究会 第50回研究会、2024年11月

<a href="https://drive.google.com/file/d/1VRgXlfVUQdJwqMyaVlavbKZrQhj6o4cP/view" class="icon-link">{{< fa solid link >}} リンク</a>

福田 遥生、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「SoccerMix によるプレースタイルの分類と利用の検討」（ポスター発表）、「社会におけるAI」研究会 第50回研究会、2024年11月

<a href="https://drive.google.com/file/d/17HKk10T2WcQXrvKsOnrrLbKBKL1Z0K6r/view" class="icon-link">{{< fa solid link >}} リンク</a>

前田 綾也、鈴木 涼介、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「レスキューシミュレーションの動的環境における MaxSum 法の解振動に関する一考察」（ポスター発表）、「社会におけるAI」研究会 第50回研究会、2024年11月

<a href="https://drive.google.com/file/d/1Ti9QQ5JFNE11Kae2aAaFIJZNn76KFeGT/view" class="icon-link">{{< fa solid link >}} リンク</a>

髙林 大渡、福田 遥生、**安藤 圭祐**、伊藤 暢浩「2D サッカーゲームにおける競技観戦者向けの視覚化システムの提案」（ポスター発表）、「社会におけるAI」研究会 第50回研究会、2024年11月

<a href="https://drive.google.com/file/d/18cXqfSfjR-Cc7jc49fSE900H2DVoaOSD/view" class="icon-link">{{< fa solid link >}} リンク</a>

鈴木 宏哉、上原 温揮、藤澤 丈、前田 綾也、松永 一希、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「RRSにおけるL-DCOPを用いた異種エージェント間協調について」人工知能学会第二種研究会資料、vol. 2023、no. SAI-047、pp. 1--8 2024年5月、DOI: [10.11517/jsaisigtwo.2023.SAI-047_03](https://doi.org/10.11517/jsaisigtwo.2023.SAI-047_03)

**安藤 圭祐**、内種 岳詞、向 直人、岩田 員典、伊藤 暢浩「愛知県における交通事故特徴の空間分析」電子情報通信学会技術研究報告、vol. 123、no. 412、pp. 12--17、2024年3月

<a href="https://ken.ieice.org/ken/paper/20240303Lccu/" class="icon-link">{{< fa solid link >}} リンク</a>

松永 一希、岡本 愛、笹田 敬太郎、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「RRSのADFのモジュール間依存関係について」（ポスター発表）、「社会におけるAI」研究会 第47回研究会、2023年11月

<a href="https://drive.google.com/file/d/1ChGZdbx8H9Qx2_r8vdJPYSAX5wtTzURK/view" class="icon-link">{{< fa solid link >}} リンク</a>

鈴木 宏哉、上原 温揮、藤澤 丈、前田 綾也、松永 一希、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「RRSにおけるL-DCOPを用いた異種エージェント間協調について」（ポスター発表）、「社会におけるAI」研究会 第47回研究会、2023年11月、最優秀プレゼンテーション賞受賞

<a href="https://drive.google.com/file/d/1KbpdHOYd9QMe3pURRDYA5E4G_BLAKgpz/view" class="icon-link">{{< fa solid link >}} リンク</a>

伴 昌樹、福田 遥生、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「RSS2DにおけるExpected Possession Valueを用いた意思決定の検討」（ポスター発表）、「社会におけるAI」研究会 第47回研究会、2023年11月

<a href="https://drive.google.com/file/d/1n69eMMHClPMrghBRH52KnLY7PVJY_07t/view" class="icon-link">{{< fa solid link >}} リンク</a>

中尾 望、村上 知弘、三宅 陽、村田 颯、天野 樹、小島 大征、**安藤 圭祐**、伊藤 暢浩「人狼知能における襲撃先同調の効果について」、人工知能学会全国大会（第37回）、人工知能学会全国大会論文集（Web）、Vol. 37、pp. 1--4、2023年6月、DOI: [10.11517/pjsai.JSAI2023.0_4D2GS1101](https://doi.org/10.11517/pjsai.JSAI2023.0_4D2GS1101)

天野 樹、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「人狼知能における要請と受諾によるゲーム展開の変化」電子情報通信学会技術研究報告、vol. 122、no. 421、pp. 24--29、2023年3月

<a href="https://ken.ieice.org/ken/paper/202303118Ct0/" class="icon-link">{{< fa solid link >}} リンク</a>

天野 巧巳、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「期待ポゼッション値によるRSS2Dの試合状況分析」研究報告知能システム（ICS）、vol. 2022-ICS-210、no. 8、pp. 1--6、2023年3月

<a href="http://id.nii.ac.jp/1001/00224976/" class="icon-link">{{< fa solid link >}} リンク</a>

清水 和彦、**安藤 圭祐**、内種 岳詞、向 直人、岩田 員典、伊藤 暢浩、蒋 湧「愛知県の交通事故に対するRisk Terrain Modelingの有効性の検証」人工知能学会第二種研究会資料、vol. 2023 no. SAI-046、pp. 1--7、2023年3月．DOI: [10.11517/jsaisigtwo.2023.SAI-046_02](https://doi.org/10.11517/jsaisigtwo.2023.SAI-046_02)

清水 和彦、**安藤 圭祐**、内種 岳詞、向 直人、岩田 員典、伊藤 暢浩、蒋 湧「名古屋市中区の交通事故を対象としたRisk Terrain Modelingの適用に関する一考察」第20回情報学ワークショップ(WiNF2022)、2022年12月

<a href="https://sites.google.com/view/winf2022/" class="icon-link">{{< fa solid link >}} リンク</a>

福田 遥生、小泉 響暉、伴 昌樹、天野 巧巳、**安藤 圭祐**、伊藤 暢浩「トライデータ構造を用いたサッカーチームの分類について」（ポスター発表）、「社会におけるAI」研究会 第45回研究会、2022年12月

<a href="https://drive.google.com/file/d/1rFmO9YSP2jvGVgsiG9_Py5Sa9qQAdgZY/view" class="icon-link">{{< fa solid link >}} リンク</a>

前田 綾也、上原 温揮、松永 一希、藤澤 丈、鈴木 宏哉、**安藤 圭祐**、内種 岳詞、岩田 員典、伊藤 暢浩「RRSにおけるL-DCOPエージェントの移動時間推定に関する検討」（ポスター発表）、「社会におけるAI」研究会 第45回研究会、2022年12月

<a href="https://drive.google.com/file/d/16EXExIR02wVCrFj9Jpw-5mKSYVdbrSzJ/view" class="icon-link">{{< fa solid link >}} リンク</a>

川上 洵恩、長谷川 滉、安藤 圭祐、内種 岳詞、岩田 員典、伊藤 暢浩「情報アーキテクチャに基づくRRSViewerのUX改善」（ポスター発表）、「社会におけるAI」研究会 第45回研究会、2022年12月

<a href="https://drive.google.com/file/d/1gg-XpDXh2-7PxFoHiefyKlEeBfBVWxqJ/view" class="icon-link">{{< fa solid link >}} リンク</a>

**安藤 圭祐**、國吉 佑輔、清水 和彦、岡本 愛、伊藤 暢浩、岩田 員典、内種 岳詞、向 直人、蒋 湧「地理空間データによる交通事故の要因分析」電子情報通信学会技術研究報告、vol. 121、no. 439、pp. 19--24、2021年12月

<a href="https://ken.ieice.org/ken/paper/20220312FCjT/" class="icon-link">{{< fa solid link >}} リンク</a>
<a href="https://www.docswell.com/s/NONONOexe/K6YEVP-wssit-trafacc" class="icon-link">{{< fa solid person-chalkboard >}} Docswell</a>

**安藤 圭祐**、國吉 佑輔、清水 和彦、岡本 愛、伊藤 暢浩、岩田 員典、内種 岳詞、向 直人、蒋 湧「愛知県の交通事故発生区域のクラスタ分析」人工知能学会第二種研究会資料、vol. 2021、no. SAI-42、pp. 1--7、2021年12月．DOI: [10.11517/jsaisigtwo.2021.SAI-042_01](https://doi.org/10.11517/jsaisigtwo.2021.SAI-042_01)

**安藤 圭祐**、國吉 佑輔、清水 和彦、岡本 愛、伊藤 暢浩、岩田 員典、内種 岳詞、向 直人、蒋 湧「愛知県の交通事故発生区域のクラスタ分析」（ポスター発表）、「社会におけるAI」研究会 第42回研究会、2021年12月、最優秀プレゼンテーション賞受賞

<a href="https://drive.google.com/file/d/1nj8N7hFGrgIxA0MFWsgqQlPjz2pnXPVN/view" class="icon-link">{{< fa solid link >}} リンク</a>

天野 巧巳、清水 和彦、川添 敦都、**安藤 圭祐**、伊藤 暢浩「DX-NESを用いたRSS3Dのキック動作設計における評価式の検討」電気・電子・情報関係学会東海支部連合大会講演論文集、p. 1、2021年8月  

<a href="https://jglobal.jst.go.jp/detail?JGLOBAL_ID=202202215633408391" class="icon-link">{{< fa solid link >}} リンク</a>

加藤 翔馬、**安藤 圭祐**、伊藤 暢浩、岩田 員典、内種 岳詞、向 直人、蒋 湧「愛知県における事故件数と交通量の関係についての分析」人工知能学会第二種研究会資料、vol. 2020、no. SAI-039、pp. 6--13、2020年11月．DOI: [10.11517/jsaisigtwo.2020.SAI-039_06](https://doi.org/10.11517/jsaisigtwo.2020.SAI-039_06)

福井 敬徳、**安藤 圭祐**、村上 俊英、伊藤 暢浩、岩田 員典「人狼BBSにおける発話の自動分類」研究報告知能システム、vol. 3、pp. 1--7、2017年7月

<a href="https://www.slideshare.net/TakanoriFukui/bbs-80930597" class="icon-link">{{< fa brands slideshare >}} SlideShare</a>

## 書籍

**Keisuke ANDO**, Takeshi UCHITANE, Naoto MUKAI, Kazunori IWATA, Nobuhiro ITO, Yong JIANG, Naohiro ISHII, “Social Simulations Using Multi-agent Systems,” Springer Series in Reliability Engineering, pp. 117--133, Sep, 2024

## 競技会成績

Haruki UEHARA, Yuki SHIMADA, **Keisuke ANDO**, Takeshi UCHITANE, Kazunori IWATA, Nobuhiro ITO, RoboCup Rescue Simulation Infrastructure Competition First Place, RoboCup 2024

Ryoya MAEDA, Haruki UEHARA, Joe FUJISAWA, Itsuki MATSUNAGA, Ryosyuke SUZUKI, Kouta KATO, Yuki SHIMADA, Shuntarou FUJII, **Keisuke ANDO**, Takeshi UCHITANE, Kazunori IWATA, Nobuhiro ITO, RoboCup Rescue Simulation League Agent Competition First Place, RoboCup 2024

鈴木 涼介、**安藤 圭祐**、上原 温揮、島田 優希、伊藤 暢浩、岩田 員典、ロボカップジャパンオープン 2024 レスキューシミュレーション（Agent）, 第1位, ロボカップ日本委員会

Ayato2003（小川 滉太、門田 真一朗、塩野 佑真、林 直希、山田 航暉、日比 彩斗、山口 瑛士、川田 虎之介、水野 航汰、越田 雅治、**安藤 圭祐**），進化計算コンペティション2024、準トップ賞、産業応用特別賞

itolab（**安藤 圭祐**）、第1回人狼知能大会、2015年、決勝進出、第11位

## そのほか資料

Ryoya MAEDA, Haruki UEHARA, Joe FUJISAWA, Itsuki MATSUNAGA, Ryosuke SUZUKI, Kouta KATO, Yuki SHIMADA, Shuntarou FUJII, **Keisuke ANDO**, Takeshi UCHITANE, Kazunori IWATA and Nobuhiro ITO, “RoboCupRescue 2024 TDP Agent Simulation AIT-Rescue (Japan),” RoboCup 2024, Team Description Paper, pp. 1--15, 2024年7月

<a href="https://rescuesim.robocup.org/2024-eindhoven-agent-participating-teams/" class="icon-link">{{< fa solid link >}} リンク</a>
